# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 773b3c9d8e406356a06a231521b175401ab4f592458878f79c1f41096c2b360e00db838c9bf19cd5b2e288d45e1b9bdffb9ac8ef993c3f6a76b9ca2f829fc2e6

test:
  secret_key_base: ae7c48c5777d213891b9f38672be23289364a4ec4f7127405c0126669feaa0594f4d8369a6b7e77c9b26f97b64f757b1419acba397a49eb1a4f429a9d48e61de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
